#微信小程序配置
wx:
  miniapp:
    configs:
        - appid: wxcee462db5d5dcc77
          secret: c097890bd8143a9b75d97201b655f197
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
